plugins {
    id 'java-library'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.140'
}

base {
    archivesName = "${fileName}-${mc_version}"
}

version = version
group = modGroup

java.toolchain.languageVersion = JavaLanguageVersion.of(javaVersion)

repositories {
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url "https://maven.blamejared.com"
        content {
            includeGroup "vazkii.patchouli"
            includeGroupByRegex "net\\.darkhax.*"
            includeGroupByRegex "com\\.blamejared.*"
            includeGroup "org.openzen.zencode"
            includeGroup "mezz.jei"
        }
    }
    maven {
        // Curios
        url "https://maven.theillusivec4.top"
        content {
            includeGroupByRegex "top\\.theillusivec4.*"
        }
    }
    maven { url 'https://maven.shedaniel.me/' }
    maven { url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
    maven { url 'https://maven.kosmx.dev/' }
    maven { url "https://rtxyd.github.io/maven-repo" }
    maven {
        name = "Iron's Maven - Release"
        url = "https://code.redspace.io/releases"
    }
    maven {
        name = "Iron's Maven - Snapshots"
        url = "https://code.redspace.io/snapshots"
    }
    maven { url 'https://jitpack.io' }
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.modid
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.modid
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.modid
        }

        data {
            data()
            programArguments.addAll '--mod', project.modid, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', ''
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${modid}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    // Mixin
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    implementation "io.github.llamalad7:mixinextras-neoforge:${mixin_extras_version}"

    // Required Dependencies
    runtimeOnly "curse.maven:attributefix-280510:7115922"
    implementation "io.redspace:irons_spellbooks:${irons_spells_version}"
    compileOnly "io.redspace:irons_spellbooks:${irons_spells_version}:api"
    runtimeOnly "io.redspace:irons_spellbooks:${irons_spells_version}"
    implementation "curse.maven:irons-lib-1492763:8364894"
    implementation "curse.maven:better-combat-by-daedelus-639842:8430183"

    // Dev Env Mods
    runtimeOnly "curse.maven:mmmmmmmmmmmm-225738:8510632"
    implementation "curse.maven:jei-238222:8601660"

    // Libs
    runtimeOnly "curse.maven:cloth-config-348521:5729127"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    implementation "curse.maven:playeranimator-658587:7389814"
    implementation "curse.maven:geckolib-388172:8350073"
    implementation "curse.maven:caelus-308989:5694215"
    implementation "curse.maven:selene-499980:8510630"
    runtimeOnly "curse.maven:bookshelf-228525:7606240"
    runtimeOnly "curse.maven:prickle-1023259:6961457"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : mc_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            modid                  : modid,
            mod_name               : modName,
            mod_version            : version,
            mod_authors            : author,
            mod_description        : desc,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                "Specification-Title"     : fileName,
                "Specification-Vendor"    : author,
                "Specification-Version"   : "1.0",
                "Implementation-Title"    : fileName,
                "Implementation-Version"  : version,
                "Implementation-Vendor"   : author,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

java {
    withSourcesJar()
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}